language: python
dist: xenial
sudo: true
install:
- pip install coverage pytest-cov coveralls
- pip install -r requirements_dev.txt
after_success:
- coveralls
matrix:
  include:
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
  - name: '3.8'
    python: 3.8
  - name: 'pypy3'
    python: pypy3
script: pytest --cov=mythx_models tests/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: dmuhs
  password:
    secure: U3OchTw7vNDY/i8KEPghQnSpeGeqBw8AQJvasKCAWdqVYGnMf0WDnw3KhJLdPDXdjrGPs5SI6Zwc4q0KFwZC4acVJ/ESA+5dLLXoPNQmEWarkXuyM6hIAt6m9WJo1YKV35DQ1pdbZpEJLQoMgnm2MlrKRjXuQJnNiSQtMzwdpB6DFhZwSnEYQzCCBCEq632oh19FNhYPkJLgk9uR06J2y6oPaYch6Vk0+iLMItqIQSWIlk8SoKTF76A/+9rDfvShaQbmpEOe4K4cPs8GHDXMXnQrPcpmHBohP5pWsEKKKHU9+wqAxmUQzrIZSp999GZaZ/LIgJQh//ym4Ek3BN1TZdneoxDqFB5a5t8J03MRVj8KIqJXLNjdFo7/iWpL8VMRu6YXDUl0jxVKseSCweU9TciotveIKa7fUGGBzJZwjlE9eKIQ7tk4ZEvNGc44irlGElnugqJkZ7noEXfHsUe+ahrbD4n38BAvoYxdpRsNvCb30QmkTvH2m1jWVvyAUoPLC8Xovmndb/WrHAna9FPTTauZnU/sTMuUsifTejnzi3nxMngzRZ3SrQTJb0R0almg3cXgoFbDe4uo1ECdExA35QtJETWT5ELMXwKcnGZk9oIrlk2B9IhM9zc94BtuQG5RUfp6qdaeO/iEcEKBn8FaFbcWA3aCSxJs5XasK5xdoxw=
  on:
    tags: true
    repo: dmuhs/mythx-models
    python: 3.6
